SELECT
DRIVERPAY.DRIVER_ID,			/*driver ID*/
TLORDER.BILL_DATE,				/*date the customer was billed*/
TLORDER.DELIVERY_TRIP, 			/*trip no*/
TLORDER.CUSTOMER,				/*bill to information*/
TLORDER.CALLNAME,
TLORDER.CALLADDR1,
TLORDER.CALLCITY,
TLORDER.CALLPROV,
TLORDER.CALLPC,
TLORDER.ORIGIN,					/*shipper information*/
TLORDER.ORIGNAME,
TLORDER.ORIGADDR1,
TLORDER.ORIGCITY,
TLORDER.ORIGPROV,
TLORDER.ORIGPC,
TLORDER.DESTINATION,			/*consignee information*/
TLORDER.DESTNAME,				
TLORDER.DESTADDR1,
TLORDER.DESTCITY,
TLORDER.DESTPROV,
TLORDER.DESTPC,
TLORDER.COMMODITY,				/*commodity code*/
TLORDER.PICK_UP_TRAILER,		/*trailer type*/
TLDTL.RATE,						/*rate information*/
TLDTL.RATE_UNITS,
TLDTL.TIME_1,					/*driver pay rate*/
TLDTL.WEIGHT,					/*total weight*/
TLORDER.DISTANCE,				/*distance from PC miler*/
TLORDER.DISTANCE_UNITS,
TLORDER.CHARGES,				/*revenue information without fuel*/
TLORDER.XCHARGES,				/*FSC and accesorial charges*/
TLORDER.CREATED_BY,
TLORDER.CURRENT_STATUS			/*status of trip*/
FROM TLORDER
LEFT JOIN TLDTL
ON TLORDER.DETAIL_LINE_ID = TLDTL.ORDER_ID
LEFT JOIN DRIVERPAY
ON TLORDER.DETAIL_LINE_ID = DRIVERPAY.DETAIL_LINE_ID
WHERE TLORDER.BILL_DATE > '2013-01-10 0:00:00' 	/*start date*/
AND TLORDER.BILL_DATE < '2013-07-10 0:00:00' 	/*end date*/
AND TLORDER.CURRENT_STATUS = 'BILLD' 			/*make sure it's billed*/
AND TLORDER.SITE_ID = 'SITE18'					/*exclude van loads*/ 
ORDER BY TLORDER.ORIGIN,						/*order by origin*/
TLORDER.ORIGNAME,
TLORDER.ORIGCITY,
TLORDER.ORIGPROV,
TLORDER.DESTINATION,							/*then order by destination*/
TLORDER.DESTNAME,
TLORDER.DESTCITY,
TLORDER.DESTPROV,
TLORDER.COMMODITY,								/*then order by commodity*/
TLORDER.DISTANCE,								/*then order by distance*/
TLORDER.DISTANCE_UNITS,
TLORDER.CUSTOMER,								/*then order by bill to*/
TLORDER.CALLNAME,
TLORDER.CALLCITY,
TLORDER.CALLPROV,
TLDTL.RATE,										/*then order by rate*/
TLORDER.BILL_DATE;								/*last order by bill_date*/